window.APP_DATA = (() => {
  const weeks = [
    { id: 1, title: "Sofort weniger Kopf", short: "Runterregeln & Abstand", color: "#ff9a1f", description: "Du baust schnelle Gegenbeweise, reduzierst Reize und holst Aufmerksamkeit aus der Schleife zurück." },
    { id: 2, title: "Alltag und Beziehungen stabilisieren", short: "Sortieren & verbinden", color: "#4ed496", description: "Du machst innere Vorgänge sichtbar und baust leichtere Systeme für soziale und häusliche Situationen." },
    { id: 3, title: "Job, Körper und Bürokratie", short: "Starten & regulieren", color: "#5a8cff", description: "Du verkleinerst Einstiege, planst nach Energie und schaffst Struktur für belastende Aufgaben." },
  ];

  const days = [
    {
      day: 1, week: 1, title: "Stärken-Detektive", page: "4", duration: "5–8 Min.", toolIds: [1],
      purpose: "Dein Gehirn erinnert sich oft besonders deutlich an Fehler, unangenehme Situationen und Dinge, die vermeintlich nicht gut gelaufen sind. Heute suchst du ganz bewusst nach einem Gegenbeweis.",
      step: "Notiere einen kleinen Erfolg des heutigen Tages in drei Spalten. Auch ein sehr kleiner Erfolg zählt.",
      situation: "Du liegst abends im Bett und dein Kopf spielt den Tag wie ein peinliches Highlight-Reel ab. Statt weiterzugrübeln, sammelst du einen konkreten Gegenbeweis.",
      why: "Fakten schwächen den automatischen Negativfilter ab. Du trainierst dein Gehirn, nicht nur Fehler, sondern auch Fähigkeiten und Fortschritte wahrzunehmen.",
      fields: [
        { key: "situation", label: "Situation", type: "textarea", placeholder: "Was ist heute gelungen?" },
        { key: "strength", label: "Mein ADHS-Anteil", type: "textarea", placeholder: "Welche Stärke hat geholfen?" },
        { key: "proof", label: "Der Beweis", type: "textarea", placeholder: "Woran erkennst du den Erfolg?" },
        { key: "remember", label: "Das möchte ich mir merken", type: "textarea", wide: true, placeholder: "Ein Satz reicht." },
      ],
      close: "Ich habe heute einen Mini-Erfolg festgehalten.",
    },
    {
      day: 2, week: 1, title: "Gib deinem Kritiker einen Namen", page: "7", duration: "4 Min.", toolIds: [2],
      purpose: "Nicht jeder Gedanke, der laut und überzeugend klingt, ist wahr. Heute schaffst du Abstand zu deiner inneren Kritikerstimme.",
      step: "Gib deiner kritischen Stimme einen Namen, der sie etwas weniger mächtig wirken lässt. Wenn sie auftaucht, sag: „Ah, das ist wieder …“",
      situation: "Nach einem kleinen Fehler startet sofort der innere Kommentar: „Du bist unfähig.“ Heute erkennst du: Das ist ein Gedankensender – nicht automatisch die Wahrheit.",
      why: "Durch das Benennen entsteht psychologische Distanz. Der Gedanke wird von einer vermeintlichen Tatsache zu etwas, das du beobachten und einordnen kannst.",
      fields: [
        { key: "criticName", label: "Mein Name für die Kritikerstimme", type: "text", wide: true, placeholder: "z. B. Radio Negativ" },
        { key: "criticSaid", label: "Was hat sie gesagt?", type: "textarea", placeholder: "Der automatische Kommentar" },
        { key: "fairAnswer", label: "Was wäre eine fairere Antwort?", type: "textarea", placeholder: "Sachlich, freundlich, glaubwürdig" },
      ],
      close: "Ich habe meine Kritikerstimme heute erkannt.",
    },
    {
      day: 3, week: 1, title: "Die 3-Minuten-Dopamin-Pause", page: "18", duration: "3 Min.", toolIds: [3],
      purpose: "Dein Gehirn bekommt ständig neue Reize. Heute unterbrichst du diesen Kreislauf für drei Minuten.",
      step: "Lege dein Handy weg, konsumiere keine neuen Inhalte, höre keine Musik oder Podcasts und sitze oder stehe einfach still. Du musst nichts lösen.",
      situation: "Du feilst ewig an einer Nachricht, öffnest immer wieder neue Apps oder scrollst, weil dein Kopf zu laut ist. Vor der nächsten Aktion machst du einen kurzen Reset.",
      why: "Weniger Reize können Überstimulation reduzieren. Dein Gehirn erhält eine kurze Pause, bevor du eine bewusste Entscheidung triffst.",
      timer: { seconds: 180, label: "Dopamin-Pause", mode: "countdown" },
      fields: [
        { key: "beforeFeeling", label: "Vor der Pause fühlt sich mein Kopf an wie", type: "radio", wide: true, options: ["ruhig", "unruhig", "überladen", "rastlos"] },
        { key: "afterChange", label: "Was hat sich danach verändert?", type: "textarea", wide: true, placeholder: "Auch „noch nichts“ ist eine gültige Beobachtung." },
      ],
      close: "Ich habe meine 3-Minuten-Pause gemacht.",
    },
    {
      day: 4, week: 1, title: "5–4–3–2–1: Zurück ins Hier und Jetzt", page: "20", duration: "3–5 Min.", toolIds: [4],
      purpose: "Wenn alles zu viel wird, kann dein Sinnesfokus dir helfen, wieder Kontakt zur Gegenwart aufzunehmen.",
      step: "Benenne 5 Dinge, die du siehst, 4 die du fühlst, 3 die du hörst, 2 die du riechst und 1 Sache, die du schmeckst. Bei wenig Zeit: 3–2–1.",
      situation: "Im Supermarkt, in öffentlichen Verkehrsmitteln oder im Büro wird plötzlich alles zu viel. Geräusche, Menschen und Gedanken vermischen sich.",
      why: "Die bewusste Verarbeitung von Sinneseindrücken bindet Aufmerksamkeit und kann Gedankenschleifen unterbrechen.",
      fields: [
        { key: "see", label: "5 Dinge, die ich sehe", type: "textarea", placeholder: "Stichpunkte reichen" },
        { key: "feel", label: "4 Dinge, die ich fühle", type: "textarea", placeholder: "z. B. Füße im Schuh" },
        { key: "hear", label: "3 Dinge, die ich höre", type: "textarea" },
        { key: "smell", label: "2 Dinge, die ich rieche", type: "textarea" },
        { key: "taste", label: "1 Sache, die ich schmecke", type: "text", wide: true },
      ],
      close: "Ich habe die Erdungstechnik heute ausprobiert.",
    },
    {
      day: 5, week: 1, title: "Dein persönliches Sensorik-Audit", page: "31", duration: "7 Min.", toolIds: [5],
      purpose: "Manche Belastungen wirken klein, begleiten dich aber über Stunden. Heute suchst du nach versteckten Stressquellen.",
      step: "Notiere drei Reize, die dich regelmäßig belasten, und wähle einen davon für eine Sofortmaßnahme.",
      situation: "Du bist scheinbar grundlos gereizt. Tatsächlich kämpft dein Nervensystem vielleicht seit Stunden mit grellem Licht, Lärm oder unangenehmer Kleidung.",
      why: "Weniger belastende Reize bedeuten weniger Dauerstress. Dadurch muss dein Gehirn seltener mit Grübeln, Rückzug oder innerer Anspannung reagieren.",
      fields: [
        { key: "trigger1", label: "Stressreiz 1", type: "text", placeholder: "Reiz · Ort · mögliche Hilfe" },
        { key: "trigger2", label: "Stressreiz 2", type: "text", placeholder: "Reiz · Ort · mögliche Hilfe" },
        { key: "trigger3", label: "Stressreiz 3", type: "text", placeholder: "Reiz · Ort · mögliche Hilfe" },
        { key: "reduceNow", label: "Diesen Reiz reduziere ich heute", type: "textarea", wide: true, placeholder: "So konkret und klein wie möglich" },
      ],
      close: "Ich habe heute mindestens einen Stressreiz reduziert.",
    },
    {
      day: 6, week: 1, title: "Deine Safe-Space-Box", page: "33", duration: "8 Min.", toolIds: [6],
      purpose: "In überfordernden Momenten brauchst du keine komplizierte Lösung. Du brauchst Hilfsmittel, die sofort erreichbar sind.",
      step: "Wähle mindestens zwei Dinge für deine persönliche Safe-Space-Box. Sie sollte leicht erreichbar sein – nicht perfekt verstaut.",
      situation: "Nach einem langen sozialen Tag bist du kurz vor einem Shutdown oder Meltdown. Statt dich weiter zusammenzureißen, greifst du zu deiner vorbereiteten Box.",
      why: "In starker Überforderung ist zusätzliche Willenskraft oft nicht verfügbar. Eine vorbereitete Box senkt die Hürde zur schnellen Reizreduktion.",
      fields: [
        { key: "boxItems", label: "Meine Auswahl", type: "checkbox", wide: true, options: ["Ohrstöpsel", "Kopfhörer", "Schlafmaske", "Sonnenbrille", "Duftanker", "Fidget/Knetball", "weicher Gegenstand", "Lieblingssnack", "beruhigende Karte"] },
        { key: "boxPlace", label: "Wo liegt meine Box?", type: "text", placeholder: "Sichtbar und erreichbar" },
        { key: "calmingSentence", label: "Mein beruhigender Satz", type: "textarea", placeholder: "Ich darf mich jetzt regulieren …" },
      ],
      close: "Meine Safe-Space-Box ist einsatzbereit.",
    },
    {
      day: 7, week: 1, title: "Die Ideen-Schleuse", page: "45", duration: "6 Min.", toolIds: [7],
      purpose: "Neue Ideen und Aufgaben müssen nicht sofort bearbeitet werden. Heute gibst du ihnen einen sicheren Parkplatz.",
      step: "Notiere fünf Gedanken, Ideen oder To-dos jeweils in einem Satz und lege eine feste Sichtungszeit fest. Bis dahin dürfen sie liegen bleiben.",
      situation: "Während der Arbeit tauchen ständig neue Ideen auf. Statt jeder Idee hinterherzulaufen, parkst du sie.",
      why: "Das Aufschreiben entlastet dein Arbeitsgedächtnis. Dein Gehirn muss die Gedanken nicht dauerhaft aktiv halten, um sie nicht zu vergessen.",
      fields: [
        { key: "park1", label: "Gedanke 1", type: "text" }, { key: "park2", label: "Gedanke 2", type: "text" },
        { key: "park3", label: "Gedanke 3", type: "text" }, { key: "park4", label: "Gedanke 4", type: "text" },
        { key: "park5", label: "Gedanke 5", type: "text" }, { key: "reviewTime", label: "Meine Sichtungszeit", type: "time" },
        { key: "weekOneTool", label: "Rückblick: Welches Tool half bisher am meisten?", type: "textarea", wide: true },
      ],
      close: "Ich habe heute meine Ideen-Schleuse benutzt.",
    },
    {
      day: 8, week: 2, title: "Analoges Mind-Mapping", page: "47", duration: "5 Min.", toolIds: [8],
      purpose: "Wenn alles miteinander verknotet wirkt, musst du nicht sofort eine Lösung finden. Zuerst machst du das Chaos sichtbar.",
      step: "Schreibe dein Hauptthema in die Mitte eines Blatts, zeichne fünf Äste und stoppe nach fünf Minuten. Die Mindmap ist dann fertig genug.",
      situation: "Job, Haushalt, Termine und Beziehungen kleben in deinem Kopf zusammen. Die Mindmap macht aus einem großen Knoten erkennbare Bereiche.",
      why: "Sichtbare Informationen lassen sich leichter sortieren als ein unscharfes Gefühl von „zu viel“. Du musst nicht alles gleichzeitig im Arbeitsgedächtnis halten.",
      timer: { seconds: 300, label: "Mindmap", mode: "countdown" },
      fields: [
        { key: "topic", label: "Mein heutiges Hauptthema", type: "text", wide: true },
        { key: "branch1", label: "Ast 1", type: "text" }, { key: "branch2", label: "Ast 2", type: "text" },
        { key: "branch3", label: "Ast 3", type: "text" }, { key: "branch4", label: "Ast 4", type: "text" },
        { key: "branch5", label: "Ast 5", type: "text" },
        { key: "clearer", label: "Eine Sache, die jetzt klarer ist", type: "textarea", wide: true },
      ],
      close: "Ich habe meine 5-Minuten-Mindmap erstellt.",
    },
    {
      day: 9, week: 2, title: "Die Unmasking-Ampel", page: "57", duration: "7 Min.", toolIds: [9],
      purpose: "Nicht jede Umgebung fühlt sich gleich sicher an. Heute untersuchst du, wo du dich zeigen kannst und wo du besonders viel Energie verbrauchst.",
      step: "Ordne drei Lebensbereiche einer Ampelfarbe zu: Grün – ich selbst; Gelb – teilweise angepasst; Rot – starke Kontrolle.",
      situation: "Nach einem Treffen bist du völlig leer und analysierst stundenlang, wie du gewirkt hast. Die Ampel macht den Energiepreis sichtbar.",
      why: "Du steuerst deine Energie bewusster. Statt dich überall zum Durchhalten zu zwingen, kannst du soziale Belastung und Erholung besser ausbalancieren.",
      fields: [
        { key: "green", label: "🟢 Grün · Hier kann ich ich selbst sein", type: "textarea" },
        { key: "yellow", label: "🟡 Gelb · Hier passe ich mich teilweise an", type: "textarea" },
        { key: "red", label: "🔴 Rot · Hier kontrolliere ich mich stark", type: "textarea" },
        { key: "recovery", label: "Nach Gelb oder Rot plane ich", type: "textarea", wide: true, placeholder: "Eine kleine Erholung oder Grenze" },
      ],
      close: "Ich habe drei Kontexte eingeordnet.",
    },
    {
      day: 10, week: 2, title: "SOS bei RSD", page: "58", duration: "4 Min.", toolIds: [10],
      purpose: "Eine kurze Nachricht, ein fehlendes Emoji oder eine verspätete Antwort kann sich wie Ablehnung anfühlen. Heute baust du eine Pause zwischen Gefühl und Reaktion ein.",
      step: "1. Benennen: „Das könnte gerade RSD sein.“ 2. Zwei neutrale Erklärungen finden. 3. Zeitbremse: Morgen entscheiden, ob und wie du reagierst.",
      situation: "Jemand antwortet nicht oder ungewöhnlich kurz. Dein Kopf macht daraus sofort Ablehnung. Heute behandelst du diese Interpretation nicht als Tatsache.",
      why: "Die SOS-Technik trennt Beobachtung und Interpretation. Die Zeitbremse verringert das Risiko, impulsiv zu schreiben oder vorschnell zu bewerten.",
      fields: [
        { key: "facts", label: "Was weiß ich tatsächlich?", type: "textarea", wide: true, placeholder: "Nur beobachtbare Fakten" },
        { key: "neutral1", label: "Neutrale Erklärung 1", type: "textarea", placeholder: "Vielleicht …" },
        { key: "neutral2", label: "Neutrale Erklärung 2", type: "textarea", placeholder: "Vielleicht …" },
        { key: "tomorrow", label: "Wenn es morgen noch wichtig ist, dann …", type: "textarea", wide: true },
      ],
      close: "Ich habe heute mindestens eine neutrale Erklärung gesucht.",
    },
    {
      day: 11, week: 2, title: "Die Time-out-Geste", page: "69", duration: "5 Min.", toolIds: [11],
      purpose: "Ein Time-out ist kein Weglaufen. Es ist eine bewusste Unterbrechung, bevor ein Gespräch eskaliert.",
      step: "Lege deinen Time-out-Satz, eine Rückkehrzeit und eine einfache Geste fest. Die Rückkehrzeit signalisiert: Das Gespräch wird später fortgesetzt.",
      situation: "Ein Gespräch kippt. Dein Körper wird heiß, das Herz schlägt schneller und du merkst: Gleich sage ich etwas, das mir später leidtut.",
      why: "Die Pause senkt den Stresspegel. Die vereinbarte Rückkehrzeit gibt gleichzeitig Sicherheit und hält die Verbindung offen.",
      fields: [
        { key: "timeoutSentence", label: "Mein Time-out-Satz", type: "textarea", wide: true, placeholder: "Time-out. Ich brauche eine Pause und komme um … zurück." },
        { key: "returnTime", label: "Rückkehrzeit", type: "time" },
        { key: "gesture", label: "Meine Geste", type: "radio", options: ["flache Hand", "Hand aufs Herz", "vereinbartes Wort", "andere Geste"] },
        { key: "bodySignal", label: "Mein Warnsignal im Körper", type: "textarea", wide: true },
      ],
      close: "Ich habe meinen Satz und meine Rückkehrzeit festgelegt.",
    },
    {
      day: 12, week: 2, title: "Der Dopamin-Check-in", page: "71", duration: "6 Min.", toolIds: [12],
      purpose: "Beziehungen bestehen nicht nur aus Organisation, Aufgaben und Problemlösung. Heute schaffst du bewusst Raum für Verbindung.",
      step: "Beantworte drei Fragen – allein oder gemeinsam mit einer vertrauten Person: Was war gut? Was war schwer? Was brauche ich gerade?",
      situation: "Eine Beziehung fühlt sich nur noch wie Organisation an. Der Check-in bringt persönliche Wahrnehmung und Verbindung zurück ins Gespräch.",
      why: "Positive Momente bekommen bewusst Raum. Bedürfnisse können angesprochen werden, bevor sie sich in Frust oder Grübeln verwandeln.",
      fields: [
        { key: "good", label: "Was war heute gut?", type: "textarea" },
        { key: "hard", label: "Was war heute schwer?", type: "textarea" },
        { key: "need", label: "Was brauche ich gerade?", type: "textarea" },
        { key: "gratitude", label: "Eine Sache, für die ich dankbar bin", type: "textarea", wide: true },
      ],
      close: "Ich habe meinen Dopamin-Check-in gemacht.",
    },
    {
      day: 13, week: 2, title: "Das System der minimalen Reibung", page: "83", duration: "8 Min.", toolIds: [13],
      purpose: "Ein gutes Alltagssystem muss nicht schön, clever oder perfekt sein. Es muss für dein tatsächliches Leben funktionieren.",
      step: "Wähle eine Stelle, an der regelmäßig etwas schiefläuft. Heute versuchst du nicht, disziplinierter zu werden – du baust die Hürde ab.",
      situation: "Schlüssel, Briefe oder Wäsche landen am falschen Ort. Jeder neue Fehler löst Scham und Selbstkritik aus.",
      why: "Weniger Reibung erhöht die Wahrscheinlichkeit, dass eine Handlung ausgeführt wird. Ein funktionierendes System reduziert wiederkehrende Schamspiralen.",
      fields: [
        { key: "frictionArea", label: "Wo hakt es?", type: "radio", wide: true, options: ["Schlüssel", "Post", "Wäsche", "Medikamente", "Müll", "Einkauf", "Ladekabel", "etwas anderes"] },
        { key: "oldProblem", label: "Das bisherige Problem", type: "textarea" },
        { key: "simplify", label: "So mache ich es einfacher", type: "checkbox", options: ["näher am Einsatzort", "sichtbar", "offen", "doppelt vorhanden", "in einem Behälter"] },
        { key: "newRule", label: "Meine neue Ein-Satz-Regel", type: "textarea", wide: true, placeholder: "Ab heute kommt … direkt …" },
      ],
      close: "Ich habe heute ein Alltagssystem vereinfacht.",
    },
    {
      day: 14, week: 2, title: "Der sichtbare Blitz-Reset", page: "85", duration: "5 Min.", toolIds: [14],
      purpose: "Du musst nicht die ganze Wohnung aufräumen. Heute erzeugst du in kurzer Zeit ein sichtbares Ergebnis.",
      step: "Stelle fünf Minuten und wähle genau eine Mini-Aufgabe. Nicht sortieren, nicht perfektionieren, kein Nebenprojekt – beim Klingeln aufhören.",
      situation: "Das Chaos wirkt so groß, dass du gar nicht beginnst. Ein kleiner sichtbarer Reset beweist deinem Gehirn: Veränderung ist möglich.",
      why: "Ein direkt sichtbares Ergebnis senkt Stress und stärkt dein Handlungsgefühl. Der kurze Timer macht den Einstieg überschaubar.",
      timer: { seconds: 300, label: "Blitz-Reset", mode: "countdown" },
      fields: [
        { key: "resetTask", label: "Meine eine Aufgabe", type: "radio", wide: true, options: ["eine Fläche freiräumen", "zehn Dinge wegräumen", "Müll einsammeln", "Kleidung sammeln", "Geschirr sammeln", "andere Mini-Aufgabe"] },
        { key: "resetArea", label: "Mein Bereich", type: "text", wide: true },
        { key: "weekTwoChange", label: "Rückblick: Was ist im Alltag schon etwas leichter?", type: "textarea", wide: true },
      ],
      close: "Ich habe heute meinen Blitz-Reset gemacht.",
    },
    {
      day: 15, week: 3, title: "Eat the Frog – ADHS-gerecht", page: "97", duration: "3 Min.", toolIds: [15],
      purpose: "Die wichtigste Aufgabe des Tages fühlt sich häufig besonders schwer an. Heute musst du sie nicht erledigen – du musst sie nur beginnen.",
      step: "Definiere einen Startschritt, der höchstens eine Minute dauert: Dokument öffnen, Betreffzeile schreiben, Datei oder Nummer suchen.",
      situation: "Du bist den ganzen Tag mit Kleinigkeiten beschäftigt, während die wichtigste Aufgabe liegen bleibt. Heute machst du den Einstieg winzig.",
      why: "Ein Mini-Start reduziert den wahrgenommenen Aufwand. Sobald du begonnen hast, kann Momentum entstehen – du darfst aber auch nach dem ersten Schritt aufhören.",
      fields: [
        { key: "frog", label: "Mein heutiger Frosch", type: "textarea", wide: true },
        { key: "microStart", label: "Der kleinstmögliche Startschritt", type: "textarea", placeholder: "Maximal eine Minute" },
        { key: "afterStart", label: "Was passierte danach?", type: "textarea" },
      ],
      close: "Ich habe meinen Ein-Minuten-Schritt ausgeführt.",
    },
    {
      day: 16, week: 3, title: "Fokus-Sprint und Body Doubling", page: "99", duration: "5–10 Min.", toolIds: [16],
      purpose: "Du brauchst nicht immer mehr Motivation. Manchmal brauchst du einen klaren Anfang, eine kurze Zeitspanne und die Anwesenheit einer anderen Person.",
      step: "Wähle eine Aufgabe, eine Sprintdauer und optional ein Body Double. Bearbeite nur diese Aufgabe; Ablenkungen werden notiert, nicht verfolgt.",
      situation: "Du möchtest anfangen, landest aber beim Scrollen, Herumlaufen oder Vorbereiten. Der kurze Sprint begrenzt die Aufgabe zeitlich.",
      why: "Ein überschaubares Zeitlimit verringert Überforderung. Body Doubling kann zusätzliche äußere Struktur und Verbindlichkeit schaffen.",
      timer: { seconds: 420, label: "Fokus-Sprint", mode: "countdown", choices: [300, 420, 600] },
      fields: [
        { key: "focusTask", label: "Meine eine Aufgabe", type: "textarea", wide: true },
        { key: "bodyDouble", label: "Mein Body Double", type: "radio", wide: true, options: ["Person im Raum", "Videoanruf", "Online-Fokusraum", "Arbeite-mit-mir-Video", "heute nicht nötig"] },
        { key: "distractions", label: "Geparkte Ablenkungen", type: "textarea" },
        { key: "sprintResult", label: "Mein Ergebnis nach dem Sprint", type: "textarea" },
      ],
      close: "Ich habe heute mindestens einen Fokus-Sprint gemacht.",
    },
    {
      day: 17, week: 3, title: "Plane nach deiner Energie", page: "111", duration: "4 Min.", toolIds: [17],
      purpose: "Nicht jeder Tag bietet dieselbe Energie. Heute passt du mindestens eine Erwartung an deinen tatsächlichen Zustand an.",
      step: "Wähle LOW, MEDIUM oder HIGH. Bei LOW reduzierst du, bei MEDIUM erledigst du Routinen, bei HIGH nutzt du anspruchsvolle oder kreative Aufgaben.",
      situation: "In PMS-, Stress- oder Low-Phasen wird alles lauter. Trotzdem erwartest du dieselbe Leistung wie an einem guten Tag – und verurteilst dich, wenn sie ausbleibt.",
      why: "Energieorientierte Planung ersetzt den Kampf gegen den eigenen Zustand durch eine realistischere Steuerung des Tages.",
      fields: [
        { key: "energy", label: "Meine Energie heute", type: "radio", wide: true, options: ["LOW · wenig Energie", "MEDIUM · normale Aufgaben möglich", "HIGH · gute Konzentration"] },
        { key: "adjustExpectation", label: "Diese Erwartung passe ich an", type: "textarea" },
        { key: "goodEnough", label: "Das darf heute gut genug sein", type: "textarea" },
      ],
      close: "Ich habe eine Erwartung an mein Energieniveau angepasst.",
    },
    {
      day: 18, week: 3, title: "Dein Energie-Stabilisator", page: "113", duration: "5 Min.", toolIds: [18],
      purpose: "Wenn dein Körper zu wenig Flüssigkeit oder regelmäßige Nahrung bekommt, kann sich auch dein Kopf unruhiger anfühlen. Heute bereitest du eine einfache Stabilisierung vor.",
      step: "Plane einen sichtbaren Flüssigkeitsanker sowie einen Protein-Snack oder eine feste Zwischenmahlzeit für den Tag.",
      situation: "Am Nachmittag kommt der Crash. Du wirst gereizter, grübelst stärker oder suchst schnelle Reize. Heute planst du vorher, statt erst im Tief zu reagieren.",
      why: "Eine regelmäßige Versorgung kann zu stabilerer Energie beitragen und so einen zusätzlichen Belastungsfaktor für innere Unruhe reduzieren.",
      note: "Nahrungsergänzungsmittel oder größere Ernährungsumstellungen bitte bei gesundheitlichen Fragen mit einer qualifizierten Fachperson besprechen.",
      fields: [
        { key: "hydration", label: "Mein Flüssigkeitsanker", type: "radio", wide: true, options: ["Flasche sichtbar", "Erinnerung stellen", "Getränk an den Arbeitsplatz"] },
        { key: "snack", label: "Mein Snack / meine Zwischenmahlzeit", type: "text" },
        { key: "snackTime", label: "Mein Zeitpunkt", type: "time" },
        { key: "visiblePlace", label: "Mein sichtbarer Aufbewahrungsort", type: "text", wide: true },
      ],
      close: "Mein Stabilisator ist vorbereitet.",
    },
    {
      day: 19, week: 3, title: "90 Sekunden physisch entladen", page: "123", duration: "90 Sek.", toolIds: [19],
      purpose: "Starke Anspannung steckt nicht nur in deinen Gedanken. Sie zeigt sich auch im Körper. Heute leitest du diese Energie zuerst körperlich ab.",
      step: "Zehn Kniebeugen, zwanzig Sekunden ausschütteln oder gehen, noch einmal zehn Kniebeugen. Passe alles an deinen Körper und deine Möglichkeiten an.",
      situation: "Du spürst Wut, Frust oder einen starken Impuls und möchtest sofort reagieren. Vorher bewegst du deinen Körper für 90 Sekunden.",
      why: "Bewegung kann körperliche Anspannung reduzieren. Dadurch entsteht eine kurze Unterbrechung zwischen Impuls und Reaktion.",
      timer: { seconds: 90, label: "Physische Pause", mode: "countdown" },
      fields: [
        { key: "movement", label: "Meine sichere Variante", type: "radio", wide: true, options: ["Kniebeugen", "schnelles Gehen", "Wanddrücken", "kräftig ausschütteln"] },
        { key: "sequence", label: "Sequenz", type: "checkbox", wide: true, options: ["erste Bewegung", "20 Sekunden ausschütteln/gehen", "zweite Bewegung"] },
      ],
      close: "Ich habe vor meiner Reaktion eine körperliche Pause gemacht.",
    },
    {
      day: 20, week: 3, title: "Box Breathing", page: "126", duration: "2 Min.", toolIds: [20],
      purpose: "Vor schwierigen Telefonaten, Feedback oder Behördengängen kann dein Körper bereits Alarm schlagen. Heute regulierst du zuerst deinen Atem.",
      step: "Atme vier Sekunden ein, halte vier, atme vier aus, halte vier. Atme ohne Druck und verkürze die Zeiten, wenn vier Sekunden unangenehm sind.",
      situation: "Vor einem Telefonat, einer Rückmeldung oder einem Behördentermin steigt der Alarm so stark, dass du die Aufgabe vermeidest.",
      why: "Langsames, bewusstes Atmen kann dem Körper ein Signal zur Beruhigung geben und die wahrgenommene Alarmstufe senken.",
      timer: { seconds: 120, label: "Box Breathing", mode: "breathing" },
      fields: [
        { key: "nextTask", label: "Meine Aufgabe direkt nach der Atmung", type: "textarea", wide: true, placeholder: "Ein kleiner nächster Schritt" },
      ],
      close: "Ich habe zwei Minuten bewusst geatmet.",
    },
    {
      day: 21, week: 3, title: "Drei Kisten und ein Telefon-Skript", page: "150 und 153", duration: "10 Min.", toolIds: [23, 24],
      purpose: "Bürokratische Aufgaben werden leichter, wenn du nicht alles gleichzeitig entscheiden musst. Heute trennst du Sortieren und Handeln.",
      step: "Ordne ein Dokument in JETZT, WARTEN oder ARCHIV ein. Schreibe danach drei einfache Sätze für einen möglichen Anruf.",
      situation: "Ein Brief liegt seit Wochen ungeöffnet da. Gleichzeitig blockiert dich der Gedanke an einen möglichen Anruf. Heute zerlegst du beides in kleine Schritte.",
      why: "Das System reduziert Entscheidungslast. Das Skript verhindert, dass du während des Telefonats alle wichtigen Informationen spontan im Kopf halten musst.",
      fields: [
        { key: "document", label: "Mein heutiges Dokument", type: "text", wide: true },
        { key: "box", label: "Meine Kiste", type: "radio", wide: true, options: ["📥 JETZT · Handlung nötig", "⏳ WARTEN · Antwort/Frist offen", "📁 ARCHIV · nur aufbewahren"] },
        { key: "callReason", label: "1. Ich rufe an wegen …", type: "textarea" },
        { key: "reference", label: "2. Aktenzeichen / Kundennummer", type: "text" },
        { key: "request", label: "3. Ich brauche folgende Information …", type: "textarea", wide: true },
        { key: "bestTool", label: "Das hilfreichste Tool war", type: "textarea" },
        { key: "keepTool", label: "Dieses Tool möchte ich weiterverwenden", type: "textarea" },
        { key: "proud", label: "Darauf bin ich stolz", type: "textarea", wide: true },
      ],
      close: "Ich habe den 21-Tage-Plan abgeschlossen.",
    },
  ];

  const tools = [
    [1, "Stärken-Detektive", "Selbstwert", 1, "Fakten gegen den automatischen Negativfilter sammeln.", "4"],
    [2, "Kritiker benennen", "Gedanken", 2, "Abstand zwischen dir und der kritischen Stimme schaffen.", "7"],
    [3, "Dopamin-Pause", "Akut", 3, "Drei Minuten neue Reize stoppen.", "18"],
    [4, "5–4–3–2–1-Erdung", "Akut", 4, "Aufmerksamkeit über die Sinne ins Jetzt holen.", "20"],
    [5, "Sensorik-Audit", "Reize", 5, "Versteckte Stressquellen erkennen und reduzieren.", "31"],
    [6, "Safe-Space-Box", "Reize", 6, "Sofort erreichbare Hilfsmittel vorbereiten.", "33"],
    [7, "Ideen-Schleuse", "Fokus", 7, "Gedanken sicher parken, statt ihnen sofort zu folgen.", "45"],
    [8, "Analoges Mind-Mapping", "Fokus", 8, "Einen inneren Knoten sichtbar sortieren.", "47"],
    [9, "Unmasking-Ampel", "Beziehung", 9, "Den Energiepreis verschiedener Umgebungen erkennen.", "57"],
    [10, "SOS bei RSD", "Akut", 10, "Beobachtung, Interpretation und Reaktion trennen.", "58"],
    [11, "Time-out-Geste", "Beziehung", 11, "Eskalation unterbrechen und sicher zurückkehren.", "69"],
    [12, "Dopamin-Check-in", "Beziehung", 12, "Gutes, Schweres und Bedürfnisse besprechbar machen.", "71"],
    [13, "Minimale Reibung", "Alltag", 13, "Systeme an das echte Leben anpassen.", "83"],
    [14, "15-Minuten-Blitz-Routine", "Alltag", 14, "Über einen kurzen sichtbaren Reset ins Handeln kommen.", "85"],
    [15, "Eat the Frog · ADHS-modifiziert", "Job", 15, "Die Hürde auf einen Ein-Minuten-Start verkleinern.", "97"],
    [16, "Fokus-Timer & Body Doubling", "Job", 16, "Zeitbegrenzung und äußere Struktur kombinieren.", "99"],
    [17, "Cycle-Planner", "Energie", 17, "Erwartungen an die aktuelle Energie anpassen.", "111"],
    [18, "Ernährung & Dopamin-Unterstützung", "Energie", 18, "Einfache, sichtbare Energie-Stabilisatoren planen.", "113"],
    [19, "Physisches Entladen", "Akut", 19, "Starke körperliche Aktivierung vor einer Reaktion senken.", "123"],
    [20, "Box Breathing", "Akut", 20, "Über bewusstes Atmen die Alarmstufe senken.", "126"],
    [21, "Parallel Working", "Beziehung", null, "Wichtige Gespräche bei leichter gemeinsamer Bewegung führen.", "138"],
    [22, "Bedürfnis-Übersetzungs-Liste", "Beziehung", null, "Sichtbares Verhalten und innere Realität gemeinsam übersetzen.", "140"],
    [23, "Drei-Kisten-Sortiersystem", "Bürokratie", 21, "Post mit nur drei Entscheidungen vorsortieren.", "150"],
    [24, "Telefon-Skript", "Bürokratie", 21, "Wichtige Sätze vor einem Behördentelefonat festhalten.", "153"],
    [25, "Bedürfnis-Manifest", "Selbstvertretung", null, "Eigene Anforderungen konkret und kommunizierbar machen.", "167"],
    [26, "Netzwerkaufbau", "Selbstvertretung", null, "Unterstützung mit niedriger Reizhürde bewusst aufbauen.", "169"],
  ].map(([id, title, category, day, summary, page]) => ({ id, title, category, day, summary, page }));

  const supportTools = {
    21: {
      intro: "Nebeneinander kann für ein ADHS-Gehirn leichter sein als Gegenübersitzen. Eine einfache Tätigkeit liefert genug Aktivierung, damit der Gesprächskanal frei bleibt.",
      steps: ["Wählt eine leichte Paralleltätigkeit: Spaziergang, Kochen oder Sortieren.", "Kündige an: „Ich möchte dir etwas Wichtiges erzählen.“", "Erwartet keinen dauernden Blickkontakt.", "Nutzt das Format auch außerhalb von Konflikten."],
    },
    22: {
      intro: "Die Liste macht Übersetzungsfehler sichtbar, bevor daraus Schuldzuweisungen werden.",
      steps: ["Was ich tue: das sichtbare Verhalten.", "Was du vielleicht denkst: die mögliche Interpretation.", "Was tatsächlich passiert: die ADHS-Realität.", "Beginnt mit drei wiederkehrenden Situationen."],
    },
    25: {
      intro: "Ein Bedürfnis wird leichter verhandelbar, wenn es konkret statt diffus formuliert ist.",
      steps: ["Was brauche ich, um gut zu funktionieren?", "Woran merke ich, dass es fehlt?", "Welche kleine, konkrete Anpassung hilft?", "Teile zuerst nur einen Punkt mit einer sicheren Person."],
    },
    26: {
      intro: "Unterstützung muss nicht laut oder dauerhaft sein. Ein kleiner, verlässlicher Kontakt ist ein echtes Netzwerk.",
      steps: ["Wähle genau eine Person, Gruppe oder Fachstelle.", "Schalte bei Online-Gruppen Benachrichtigungen aus.", "Plane eine niedrige Frequenz, z. B. einmal pro Woche.", "Mitlesen zählt – aktive Teilnahme ist keine Pflicht."],
    },
  };

  const sosRoutes = [
    { id: "noise", title: "Mein Kopf rast", subtitle: "Zu viele Gedanken oder Reize", color: "#ffae22", icon: "∞", day: 3, steps: ["Lege neue Reize für drei Minuten weg.", "Stell beide Füße auf den Boden.", "Starte die Dopamin-Pause – du musst gerade nichts lösen."] },
    { id: "overload", title: "Alles ist zu viel", subtitle: "Reizüberflutung oder Shutdown-Nähe", color: "#32d2ef", icon: "◌", day: 6, steps: ["Reduziere zuerst Licht, Geräusch oder Berührung.", "Nimm genau einen Gegenstand aus deiner Safe-Space-Box.", "Erlaube dir Rückzug, bevor du weiterentscheidest."] },
    { id: "rejection", title: "Es fühlt sich wie Ablehnung an", subtitle: "Nachricht, Blick oder fehlende Antwort", color: "#db55ff", icon: "?", day: 10, steps: ["Benenne: „Das könnte gerade RSD sein.“", "Trenne den beobachtbaren Fakt von deiner Deutung.", "Finde zwei neutrale Erklärungen und reagiere frühestens später."] },
    { id: "conflict", title: "Ein Gespräch kippt", subtitle: "Hitze, Druck oder Eskalationsgefahr", color: "#ff6271", icon: "Ⅱ", day: 11, steps: ["Nutze deine Time-out-Geste.", "Nenne eine konkrete Rückkehrzeit.", "Reguliere erst deinen Körper – löse den Inhalt später."] },
    { id: "stuck", title: "Ich komme nicht ins Tun", subtitle: "Aufgabe wirkt zu groß", color: "#50df99", icon: "›", day: 15, steps: ["Benenne nur die eine wichtige Aufgabe.", "Verkleinere den Start auf maximal eine Minute.", "Mach nur diesen Schritt. Danach darfst du neu entscheiden."] },
    { id: "impulse", title: "Ich will sofort reagieren", subtitle: "Wut, Frust oder starker Impuls", color: "#ff8d32", icon: "!", day: 19, steps: ["Lege das Handy außer Reichweite.", "Bewege dich 90 Sekunden passend zu deinem Körper.", "Bewerte die Anspannung danach erneut, erst dann die Reaktion."] },
    { id: "admin", title: "Post oder Anruf blockiert", subtitle: "Bürokratie und Fristendruck", color: "#6e91ff", icon: "□", day: 21, steps: ["Öffne oder nimm genau ein Dokument.", "Ordne es nur in JETZT, WARTEN oder ARCHIV ein.", "Falls ein Anruf nötig ist: schreibe drei Sätze vor."] },
  ];

  return { weeks, days, tools, supportTools, sosRoutes };
})();
