"use strict";

window.ADVENTS_AMPEL_CONTENT = Object.freeze({
  phases: [
    { chapter: 1, range: "Tage 1–3", title: "Signale der Advents-Ampel", tone: "green" },
    { chapter: 2, range: "Tage 4–6", title: "Erwartungen sortieren", tone: "green" },
    { chapter: 3, range: "Tage 7–9", title: "Zeit rückwärts planen", tone: "green" },
    { chapter: 4, range: "Tage 10–12", title: "Reize rechtzeitig senken", tone: "yellow" },
    { chapter: 5, range: "Tage 13–15", title: "Termine begrenzen", tone: "yellow" },
    { chapter: 6, range: "Tage 16–18", title: "Das Minimal-Gerüst", tone: "yellow" },
    { chapter: 7, range: "Tage 19–21", title: "Abende halten", tone: "yellow" },
    { chapter: 8, range: "Tage 22–24", title: "Sätze für den Familientisch", tone: "red" },
    { chapter: 9, range: "Tage 25–27", title: "Ausstieg mit Rückkehr", tone: "red" },
    { chapter: 10, range: "Tage 28–31", title: "Sanft zwischen den Jahren", tone: "red" }
  ],
  days: [
    { day: 1, chapter: 1, title: "Die Signalkarte", expected: "green", tool: "Signale der Advents-Ampel", impulse: "Heute entsteht dein Messgerät für den ganzen Monat. In Grün dauert das zehn Minuten, in Rot entsteht es gar nicht.", reflection: "Welches der drei Signale war heute da?", duration: "2:17", audio: "audio/tag-01.mp3" },
    { day: 2, chapter: 1, title: "Zählen, nicht deuten", expected: "green", tool: "Signale der Advents-Ampel", impulse: "Heute wird nur gezählt. Dreißig Sekunden abends, ein Strich pro Signal – ohne Deutung.", reflection: "Zu welcher Tageszeit ist dir das Signal aufgefallen?", duration: "1:54", audio: "audio/tag-02.mp3" },
    { day: 3, chapter: 1, title: "Die Wenn-Rot-Zeile", expected: "green", tool: "Die Wenn-Rot-Zeile", impulse: "Heute bekommt die Karte ihre Rückseite. Die Zeile entsteht jetzt, weil in Rot nichts mehr entsteht.", reflection: "Löst deine Zeile an einem beobachtbaren Signal aus?", duration: "2:20", audio: "audio/tag-03.mp3" },
    { day: 4, chapter: 2, title: "Alles aufschreiben", expected: "green", tool: "Die Erwartungs-Streichliste", impulse: "Heute wird gesammelt und nicht entschieden. Zwanzig Minuten, und jeder Kanal wird einzeln durchgegangen.", reflection: "Wie viele Punkte stehen auf der Liste, und wie viele davon sind A?", duration: "2:01", audio: "audio/tag-04.mp3" },
    { day: 5, chapter: 2, title: "Streichen und zurückholen", expected: "green", tool: "Die Erwartungs-Streichliste", impulse: "Heute wird gestrichen, mit Stift und nicht im Kopf. Zurück kommt nur, was dir eine Begründung wert ist.", reflection: "Welchen Punkt würdest du im Januar vermissen, wenn er nie stattgefunden hätte?", duration: "2:09", audio: "audio/tag-05.mp3" },
    { day: 6, chapter: 2, title: "Der Aufschub-Satz", expected: "green", tool: "Der Aufschub-Satz", impulse: "Heute wird ein Satz vorformuliert, den du später nur noch kopierst – Wort für Wort, solange Formulieren leichtfällt.", reflection: "Welche Anfrage steht gerade offen, ohne beantwortet zu sein?", duration: "2:10", audio: "audio/tag-06.mp3" },
    { day: 7, chapter: 3, title: "Die Rückwärts-Leiste", expected: "green", tool: "Die Rückwärts-Leiste", impulse: "Heute bekommt der Dezember ein rechtes Ende. Nicht den 24., sondern dein frühestes festes Datum.", reflection: "Welcher Schritt ist dir beim Rückwärtsgehen zusätzlich eingefallen?", duration: "1:59", audio: "audio/tag-07.mp3" },
    { day: 8, chapter: 3, title: "Belegte Tage streichen", expected: "green", tool: "Die Rückwärts-Leiste", impulse: "Heute wird die Leiste an der Wirklichkeit geprüft. Was auf einem belegten Tag liegt, wandert nach links und nicht nach rechts.", reflection: "Wie viele Abende bleiben bis zu deinem festen Datum tatsächlich frei?", duration: "1:46", audio: "audio/tag-08.mp3" },
    { day: 9, chapter: 3, title: "Die Ersatzlösung", expected: "green", tool: "Die vorentschiedene Ersatzlösung", impulse: "Heute wird die Schublade gefüllt. Wer sie erst im Bedarfsfall füllt, füllt sie nicht.", reflection: "Für welche drei Namen auf deiner Liste passt die Ersatzlösung?", duration: "1:48", audio: "audio/tag-09.mp3" },
    { day: 10, chapter: 4, title: "Die Reizpause", expected: "yellow", tool: "Die 20-Minuten-Reizpause", impulse: "Heute bekommt die Pause eine Uhrzeit, und sie liegt vor dem lauten Block.", reflection: "Welches Gelb-Signal war heute da, und wann?", duration: "1:30", audio: "audio/tag-10.mp3", timer: 1200, timerLabel: "20-Minuten-Reizpause" },
    { day: 11, chapter: 4, title: "Die Stunde danach", expected: "yellow", tool: "Die 20-Minuten-Reizpause", impulse: "Die teuerste Stunde des Tages kommt nach dem lauten Block. Heute wird sie eingeplant.", reflection: "Welche Signale waren an Tagen mit Pause da, welche ohne?", duration: "1:21", audio: "audio/tag-11.mp3" },
    { day: 12, chapter: 4, title: "Der Sechzig-Sekunden-Ausstieg", expected: "yellow", tool: "Der Sechzig-Sekunden-Ausstieg", impulse: "Heute wird ein Weg festgelegt, nicht gegangen – für jeden Ort, an dem du im Dezember länger bist.", reflection: "Wo bist du im Dezember länger, ohne dass ein Weg dafür feststeht?", duration: "1:30", audio: "audio/tag-12.mp3", timer: 60, timerLabel: "60-Sekunden-Ausstieg" },
    { day: 13, chapter: 5, title: "Die Woche zählen", expected: "yellow", tool: "Die Drei-Termine-Regel", impulse: "Heute wird gezählt und nicht abgewogen. Ein Strich pro belegtem Abend, egal wie lang er ist.", reflection: "Welchen Termin hast du gestrichen, und was ist tatsächlich passiert?", duration: "1:33", audio: "audio/tag-13.mp3" },
    { day: 14, chapter: 5, title: "Von hinten streichen", expected: "yellow", tool: "Die Drei-Termine-Regel", impulse: "Heute wandert das Fenster einen Tag weiter. Der zuletzt dazugekommene Termin geht zuerst, ohne Abwägen.", reflection: "Woran hast du gemerkt, dass du doch abgewogen hast?", duration: "1:23", audio: "audio/tag-14.mp3" },
    { day: 15, chapter: 5, title: "Die Absage-Vorlage", expected: "yellow", tool: "Die Absage-Vorlage", impulse: "Heute steht die Absage fertig im Telefon. Wer sie erst im Bedarfsfall schreibt, schickt sie nicht ab.", reflection: "Welcher Termin steht als nächster auf der Kippe?", duration: "1:32", audio: "audio/tag-15.mp3" },
    { day: 16, chapter: 6, title: "Vier Zeilen", expected: "yellow", tool: "Das Minimal-Gerüst", impulse: "Heute entsteht das Blatt mit den vier Säulen. Eine Viertelstunde Papierarbeit, die in Rot nicht mehr entsteht.", reflection: "Welche der vier Säulen ist bei dir zuerst weggerutscht?" },
    { day: 17, chapter: 6, title: "Striche statt Bewertung", expected: "yellow", tool: "Das Minimal-Gerüst", impulse: "Heute wird nur abgehakt. Ein Strich hinter jede Zeile, die stattgefunden hat, ohne Kommentar dazu.", reflection: "Welche Fassung war zu groß für einen vollen Tag?" },
    { day: 18, chapter: 6, title: "Die eine Säule", expected: "yellow", tool: "Die eine Säule", impulse: "Heute wird eine Zeile unterstrichen: die, die als Letzte fällt. Diese Entscheidung triffst du jetzt, in Ruhe.", reflection: "Um welche Uhrzeit taucht dein Signal meistens auf?" },
    { day: 19, chapter: 7, title: "Die Abendklammer", expected: "yellow", tool: "Die Abendklammer", impulse: "Heute bekommen die freien Abende zwei Uhrzeiten. Ein Abend ohne Anfang hört nur auf.", reflection: "Wann fängt dein Abend an, sich zu ziehen?" },
    { day: 20, chapter: 7, title: "Eine Sache dazwischen", expected: "yellow", tool: "Die Abendklammer", impulse: "Heute wird die eine Sache für den Abend festgelegt, und zwar jetzt. Um neun ist Entscheiden teuer.", reflection: "Hat die zugehende Klammer gestern gehalten?" },
    { day: 21, chapter: 7, title: "Der feste Anker", expected: "red", tool: "Der feste Anker zur festen Uhrzeit", impulse: "Heute steht ein Punkt im Kalender, der ohne Entscheidung auskommt. Er setzt dem Abend eine Marke.", reflection: "Wie lange lag das Handy heute Abend in der Hand?" },
    { day: 22, chapter: 8, title: "Die drei Sätze", expected: "red", tool: "Die drei Sätze", impulse: "Heute werden Sätze aufgeschrieben, bevor du fährst. Am Tisch entsteht keiner mehr.", reflection: "Welcher Auslöser ist dir beim Aufschreiben zuerst eingefallen?" },
    { day: 23, chapter: 8, title: "Umleiten und aussteigen", expected: "red", tool: "Die drei Sätze", impulse: "Heute kommen die beiden anderen Sätze dazu. Einmal laut aussprechen, dann kommen sie schneller wieder.", reflection: "Wie viele der aufgeschriebenen Auslöser kamen, und welcher war neu?" },
    { day: 24, chapter: 8, title: "Der eine Satz", expected: "red", tool: "Der eine Satz", impulse: "Heute genügt ein Satz für alles. Ab dem Moment, in dem er gilt, wird nichts mehr zugeordnet.", reflection: "Wie oft war der eine Satz nötig?" },
    { day: 25, chapter: 9, title: "Der Zehn-Minuten-Ausstieg", expected: "red", tool: "Zehn-Minuten-Ausstieg", impulse: "Leg deinen Ausstieg fest, bevor der Tisch gedeckt ist. Wer wartet, bis er ihn braucht, bleibt sitzen.", reflection: "An welchem sichtbaren Verhalten hast du heute gemerkt, dass es eng wurde?", timer: 600, timerLabel: "10-Minuten-Ausstieg" },
    { day: 26, chapter: 9, title: "Die Rückkehr", expected: "red", tool: "Zehn-Minuten-Ausstieg", impulse: "Heute zählt der zweite Teil: das Zurückkommen. Zehn Minuten mit Rückkehr fallen niemandem auf, ein halber Nachmittag allen.", reflection: "Was hast du nach der Rückkehr gesagt, und würdest du es morgen wieder sagen?", timer: 600, timerLabel: "10 Minuten bis zur Rückkehr" },
    { day: 27, chapter: 9, title: "Der Grund, der bereitliegt", expected: "red", tool: "Der Grund, der bereitliegt", impulse: "Heute reichen ein Satz und ein Gegenstand. Beides liegt im Auto, bevor du losfährst.", reflection: "Welcher Grund würde bei dir eine Nachfrage auslösen?" },
    { day: 28, chapter: 10, title: "Der Tag fängt an", expected: "red", tool: "Der sanfte Wiedereinstieg", impulse: "Heute kommt eine Uhrzeit zurück, mehr nicht. Nicht das Aufstehen, sondern der Zeitpunkt, ab dem der Tag eröffnet ist.", reflection: "Was hast du dir heute vorgenommen, das aus einer Woche mit mehr Kapazität stammt?" },
    { day: 29, chapter: 10, title: "Eine Mahlzeit", expected: "red", tool: "Der sanfte Wiedereinstieg", impulse: "Heute kommt eine Mahlzeit zu fester Zeit dazu. Möglichst die, die im Januar an derselben Stelle liegt.", reflection: "Welcher Tag im Rückblick war der schwerste, und was lag an ihm anders?" },
    { day: 30, chapter: 10, title: "Zwanzig Minuten draußen", expected: "red", tool: "Der sanfte Wiedereinstieg", impulse: "Heute kommen zwanzig Minuten draußen dazu, in beliebiger Form und bei beliebigem Wetter.", reflection: "Wie lange hat es gedauert, bis du draußen warst?", timer: 1200, timerLabel: "20 Minuten draußen" },
    { day: 31, chapter: 10, title: "Der eine Punkt für Januar", expected: "red", tool: "Der eine Punkt für Januar", impulse: "Heute wird eine Zeile geschrieben und nicht elf. Mit ihr geht der Monat in Richtung Grün zu Ende.", reflection: "Wann im Februar machst du die Bilanz?" }
  ]
});
