window.APP_DATA = (() => {
  const weeks = [
    { id: 1, title: "Quiet the noise now", short: "Regulate & step back", color: "#ff9a1f", description: "You build quick counterevidence, reduce stimulation, and guide your attention out of the loop." },
    { id: 2, title: "Stabilize daily life and relationships", short: "Sort & connect", color: "#4ed496", description: "You make inner processes visible and build lighter systems for social and everyday situations." },
    { id: 3, title: "Work, body, and admin", short: "Start & regulate", color: "#5a8cff", description: "You make starting smaller, plan around your energy, and create structure for stressful tasks." },
  ];

  const days = [
    {
      day: 1, week: 1, title: "Strength Detectives", page: "20", duration: "5–8 min", toolIds: [1],
      purpose: "Your brain often remembers mistakes, uncomfortable moments, and things that seemed to go wrong especially clearly. Today, you deliberately look for counterevidence.",
      step: "Write down one small success from today in three columns. Even a very small success counts.",
      situation: "You are lying in bed while your mind replays the day like an embarrassing highlight reel. Instead of continuing to ruminate, you collect one concrete piece of counterevidence.",
      why: "Facts weaken the automatic negativity filter. You train your brain to notice not only mistakes, but also abilities and progress.",
      fields: [
        { key: "situation", label: "Situation", type: "textarea", placeholder: "What went well today?" },
        { key: "strength", label: "My ADHD contribution", type: "textarea", placeholder: "Which strength helped?" },
        { key: "proof", label: "The evidence", type: "textarea", placeholder: "How do you know it was a success?" },
        { key: "remember", label: "What I want to remember", type: "textarea", wide: true, placeholder: "One sentence is enough." },
      ],
      close: "I recorded one small success today.",
    },
    {
      day: 2, week: 1, title: "Give Your Inner Critic a Name", page: "23", duration: "4 min", toolIds: [2],
      purpose: "Not every thought that sounds loud and convincing is true. Today, you create distance from your inner critical voice.",
      step: "Give your critical voice a name that makes it feel a little less powerful. When it appears, say: ‘Ah, there goes … again.’",
      situation: "After a small mistake, the inner commentary starts immediately: ‘You are incapable.’ Today, you recognize it as a thought broadcast—not automatically the truth.",
      why: "Naming creates psychological distance. The thought changes from an apparent fact into something you can observe and put into perspective.",
      fields: [
        { key: "criticName", label: "My name for the critical voice", type: "text", wide: true, placeholder: "e.g. Negative Radio" },
        { key: "criticSaid", label: "What did it say?", type: "textarea", placeholder: "The automatic comment" },
        { key: "fairAnswer", label: "What would be a fairer response?", type: "textarea", placeholder: "Factual, kind, believable" },
      ],
      close: "I noticed my critical voice today.",
    },
    {
      day: 3, week: 1, title: "The 3-Minute Dopamine Pause", page: "34", duration: "3 min", toolIds: [3],
      purpose: "Your brain is constantly receiving new stimulation. Today, you interrupt that cycle for three minutes.",
      step: "Put your phone away, take in no new content, play no music or podcasts, and simply sit or stand still. You do not have to solve anything.",
      situation: "You keep editing a message, opening new apps, or scrolling because your mind is too loud. Before the next action, you take a short reset.",
      why: "Less input can reduce overstimulation. Your brain gets a short break before you make a conscious decision.",
      timer: { seconds: 180, label: "Dopamine pause", mode: "countdown" },
      fields: [
        { key: "beforeFeeling", label: "Before the pause, my mind feels", type: "radio", wide: true, options: ["calm", "uneasy", "overloaded", "restless"] },
        { key: "afterChange", label: "What changed afterward?", type: "textarea", wide: true, placeholder: "‘Nothing yet’ is also a valid observation." },
      ],
      close: "I took my 3-minute pause.",
    },
    {
      day: 4, week: 1, title: "5–4–3–2–1: Back to the Present", page: "37", duration: "3–5 min", toolIds: [4],
      purpose: "When everything becomes too much, focusing on your senses can help you reconnect with the present.",
      step: "Name 5 things you see, 4 you feel, 3 you hear, 2 you smell, and 1 you taste. Short on time? Use 3–2–1.",
      situation: "At the grocery store, on public transport, or at work, everything suddenly becomes too much. Sounds, people, and thoughts blend together.",
      why: "Consciously processing sensory input engages attention and can interrupt thought loops.",
      fields: [
        { key: "see", label: "5 things I see", type: "textarea", placeholder: "Bullet points are enough" },
        { key: "feel", label: "4 things I feel", type: "textarea", placeholder: "e.g. my feet inside my shoes" },
        { key: "hear", label: "3 things I hear", type: "textarea" },
        { key: "smell", label: "2 things I smell", type: "textarea" },
        { key: "taste", label: "1 thing I taste", type: "text", wide: true },
      ],
      close: "I tried the grounding technique today.",
    },
    {
      day: 5, week: 1, title: "Your Personal Sensory Audit", page: "48", duration: "7 min", toolIds: [5],
      purpose: "Some stressors seem small but stay with you for hours. Today, you look for hidden sources of stress.",
      step: "Write down three forms of input that regularly strain you, and choose one for an immediate adjustment.",
      situation: "You seem irritable for no reason. In reality, your nervous system may have been battling bright light, noise, or uncomfortable clothing for hours.",
      why: "Less stressful sensory input means less ongoing stress. Your brain has fewer reasons to respond with rumination, withdrawal, or inner tension.",
      fields: [
        { key: "trigger1", label: "Stress trigger 1", type: "text", placeholder: "Input · place · possible help" },
        { key: "trigger2", label: "Stress trigger 2", type: "text", placeholder: "Input · place · possible help" },
        { key: "trigger3", label: "Stress trigger 3", type: "text", placeholder: "Input · place · possible help" },
        { key: "reduceNow", label: "The input I will reduce today", type: "textarea", wide: true, placeholder: "As specific and small as possible" },
      ],
      close: "I reduced at least one stress trigger today.",
    },
    {
      day: 6, week: 1, title: "Your Safe-Space Box", page: "49", duration: "8 min", toolIds: [6],
      purpose: "In overwhelming moments, you do not need a complicated solution. You need aids that are immediately within reach.",
      step: "Choose at least two items for your personal safe-space box. It should be easy to reach—not perfectly stored away.",
      situation: "After a long social day, you are close to shutdown or meltdown. Instead of forcing yourself to keep going, you reach for your prepared box.",
      why: "When overwhelm is intense, extra willpower is often unavailable. A prepared box lowers the barrier to reducing stimulation quickly.",
      fields: [
        { key: "boxItems", label: "My selection", type: "checkbox", wide: true, options: ["earplugs", "headphones", "sleep mask", "sunglasses", "scent anchor", "fidget or stress ball", "soft item", "favorite snack", "calming card"] },
        { key: "boxPlace", label: "Where will I keep my box?", type: "text", placeholder: "Visible and within reach" },
        { key: "calmingSentence", label: "My calming sentence", type: "textarea", placeholder: "I am allowed to regulate now …" },
      ],
      close: "My safe-space box is ready.",
    },
    {
      day: 7, week: 1, title: "The Idea Sluice", page: "62", duration: "6 min", toolIds: [7],
      purpose: "New ideas and tasks do not need immediate attention. Today, you give them a safe place to park.",
      step: "Write down five thoughts, ideas, or to-dos in one sentence each and choose a fixed review time. Until then, they are allowed to wait.",
      situation: "New ideas keep appearing while you work. Instead of chasing each one, you park them.",
      why: "Writing them down relieves working memory. Your brain no longer has to keep the thoughts active so you will not forget them.",
      fields: [
        { key: "park1", label: "Thought 1", type: "text" }, { key: "park2", label: "Thought 2", type: "text" },
        { key: "park3", label: "Thought 3", type: "text" }, { key: "park4", label: "Thought 4", type: "text" },
        { key: "park5", label: "Thought 5", type: "text" }, { key: "reviewTime", label: "My review time", type: "time" },
        { key: "weekOneTool", label: "Review: Which tool has helped most so far?", type: "textarea", wide: true },
      ],
      close: "I used my idea sluice today.",
    },
    {
      day: 8, week: 2, title: "Analog Mind Mapping", page: "63", duration: "5 min", toolIds: [8],
      purpose: "When everything feels tangled together, you do not need an immediate solution. First, you make the chaos visible.",
      step: "Write your main topic in the center of a sheet of paper, draw five branches, and stop after five minutes. The mind map is then complete enough.",
      situation: "Work, household tasks, appointments, and relationships are stuck together in your head. The mind map turns one large knot into recognizable areas.",
      why: "Visible information is easier to sort than a vague feeling of ‘too much.’ You do not have to hold everything in working memory at once.",
      timer: { seconds: 300, label: "Mindmap", mode: "countdown" },
      fields: [
        { key: "topic", label: "My main topic today", type: "text", wide: true },
        { key: "branch1", label: "Branch 1", type: "text" }, { key: "branch2", label: "Branch 2", type: "text" },
        { key: "branch3", label: "Branch 3", type: "text" }, { key: "branch4", label: "Branch 4", type: "text" },
        { key: "branch5", label: "Branch 5", type: "text" },
        { key: "clearer", label: "One thing that is clearer now", type: "textarea", wide: true },
      ],
      close: "I created my 5-minute mind map.",
    },
    {
      day: 9, week: 2, title: "The Unmasking Traffic Light", page: "73", duration: "7 min", toolIds: [9],
      purpose: "Not every environment feels equally safe. Today, you explore where you can show up as yourself and where you use especially large amounts of energy.",
      step: "Assign three areas of your life a traffic-light color: green—fully myself; yellow—partly adapting; red—strong self-control.",
      situation: "After meeting people, you feel completely drained and spend hours analyzing how you came across. The traffic light makes the energy cost visible.",
      why: "You manage your energy more consciously. Instead of forcing yourself to endure every setting, you can balance social strain and recovery more effectively.",
      fields: [
        { key: "green", label: "🟢 Green · I can be myself here", type: "textarea" },
        { key: "yellow", label: "🟡 Yellow · I partly adapt here", type: "textarea" },
        { key: "red", label: "🔴 Red · I strongly monitor myself here", type: "textarea" },
        { key: "recovery", label: "After yellow or red, I plan", type: "textarea", wide: true, placeholder: "A small recovery step or boundary" },
      ],
      close: "I categorized three settings.",
    },
    {
      day: 10, week: 2, title: "RSD SOS", page: "75", duration: "4 min", toolIds: [10],
      purpose: "A short message, a missing emoji, or a delayed reply can feel like rejection. Today, you build a pause between feeling and response.",
      step: "1. Name it: ‘This might be RSD right now.’ 2. Find two neutral explanations. 3. Add a time brake: decide tomorrow whether and how to respond.",
      situation: "Someone does not reply or responds unusually briefly. Your mind immediately turns it into rejection. Today, you do not treat that interpretation as fact.",
      why: "The SOS technique separates observation from interpretation. The time brake reduces the risk of sending an impulsive message or judging too quickly.",
      fields: [
        { key: "facts", label: "What do I actually know?", type: "textarea", wide: true, placeholder: "Observable facts only" },
        { key: "neutral1", label: "Neutral explanation 1", type: "textarea", placeholder: "Maybe …" },
        { key: "neutral2", label: "Neutral explanation 2", type: "textarea", placeholder: "Maybe …" },
        { key: "tomorrow", label: "If it still matters tomorrow, I will …", type: "textarea", wide: true },
      ],
      close: "I looked for at least one neutral explanation today.",
    },
    {
      day: 11, week: 2, title: "The Time-Out Gesture", page: "87", duration: "5 min", toolIds: [11],
      purpose: "A time-out is not running away. It is a deliberate interruption before a conversation escalates.",
      step: "Choose your time-out sentence, a return time, and a simple gesture. The return time signals that the conversation will continue later.",
      situation: "A conversation starts to tip. Your body heats up, your heart beats faster, and you realize you are about to say something you may regret.",
      why: "The pause lowers your stress level. An agreed return time also creates safety and keeps the connection open.",
      fields: [
        { key: "timeoutSentence", label: "My time-out sentence", type: "textarea", wide: true, placeholder: "Time-out. I need a break and will come back at …" },
        { key: "returnTime", label: "Return time", type: "time" },
        { key: "gesture", label: "My gesture", type: "radio", options: ["flat hand", "hand on heart", "agreed word", "another gesture"] },
        { key: "bodySignal", label: "My warning sign in my body", type: "textarea", wide: true },
      ],
      close: "I chose my sentence and return time.",
    },
    {
      day: 12, week: 2, title: "The Dopamine Check-In", page: "89", duration: "6 min", toolIds: [12],
      purpose: "Relationships are not only about logistics, tasks, and problem-solving. Today, you intentionally create space for connection.",
      step: "Answer three questions—alone or with someone you trust: What was good? What was hard? What do I need right now?",
      situation: "A relationship feels like nothing but logistics. The check-in brings personal experience and connection back into the conversation.",
      why: "Positive moments receive deliberate space. Needs can be discussed before they turn into frustration or rumination.",
      fields: [
        { key: "good", label: "What was good today?", type: "textarea" },
        { key: "hard", label: "What was hard today?", type: "textarea" },
        { key: "need", label: "What do I need right now?", type: "textarea" },
        { key: "gratitude", label: "One thing I am grateful for", type: "textarea", wide: true },
      ],
      close: "I completed my dopamine check-in.",
    },
    {
      day: 13, week: 2, title: "The Minimum-Friction System", page: "102", duration: "8 min", toolIds: [13],
      purpose: "A good everyday system does not need to be beautiful, clever, or perfect. It needs to work for your actual life.",
      step: "Choose one place where things regularly go wrong. Today, you do not try to become more disciplined—you remove the barrier.",
      situation: "Keys, mail, or laundry end up in the wrong place. Every new mistake triggers shame and self-criticism.",
      why: "Less friction makes an action more likely to happen. A functional system reduces recurring shame spirals.",
      fields: [
        { key: "frictionArea", label: "Where does it break down?", type: "radio", wide: true, options: ["keys", "mail", "laundry", "medication", "trash", "groceries", "charging cables", "something else"] },
        { key: "oldProblem", label: "The problem so far", type: "textarea" },
        { key: "simplify", label: "How I will make it easier", type: "checkbox", options: ["closer to where it is used", "visible", "open", "keep a duplicate", "inside one container"] },
        { key: "newRule", label: "My new one-sentence rule", type: "textarea", wide: true, placeholder: "From today, … goes straight into …" },
      ],
      close: "I simplified one everyday system today.",
    },
    {
      day: 14, week: 2, title: "The Visible Flash Reset", page: "104", duration: "5 min", toolIds: [14],
      purpose: "You do not have to clean the entire home. Today, you create a visible result in a short amount of time.",
      step: "Set five minutes and choose exactly one mini-task. Do not sort, perfect, or start a side project—stop when the timer rings.",
      situation: "The mess feels so large that you do not start at all. A small, visible reset proves to your brain that change is possible.",
      why: "An immediately visible result lowers stress and strengthens your sense of agency. The short timer makes starting manageable.",
      timer: { seconds: 300, label: "Flash reset", mode: "countdown" },
      fields: [
        { key: "resetTask", label: "My one task", type: "radio", wide: true, options: ["clear one surface", "put away ten things", "collect trash", "gather clothes", "gather dishes", "another mini-task"] },
        { key: "resetArea", label: "My area", type: "text", wide: true },
        { key: "weekTwoChange", label: "Review: What already feels a little easier in daily life?", type: "textarea", wide: true },
      ],
      close: "I completed my flash reset today.",
    },
    {
      day: 15, week: 3, title: "Eat the Frog—ADHD Style", page: "117", duration: "3 min", toolIds: [15],
      purpose: "The most important task of the day often feels especially difficult. Today, you do not have to finish it—you only have to begin.",
      step: "Define a starting step that takes no more than one minute: open the document, write the subject line, or find the file or phone number.",
      situation: "You stay busy with small things all day while the most important task remains untouched. Today, you make the entry point tiny.",
      why: "A mini-start reduces perceived effort. Once you have begun, momentum may develop—but you are also allowed to stop after the first step.",
      fields: [
        { key: "frog", label: "My frog today", type: "textarea", wide: true },
        { key: "microStart", label: "The smallest possible first step", type: "textarea", placeholder: "One minute at most" },
        { key: "afterStart", label: "What happened after that?", type: "textarea" },
      ],
      close: "I completed my one-minute step.",
    },
    {
      day: 16, week: 3, title: "Focus Sprint and Body Doubling", page: "118", duration: "5–10 min", toolIds: [16],
      purpose: "You do not always need more motivation. Sometimes you need a clear beginning, a short time frame, and another person's presence.",
      step: "Choose one task, a sprint duration, and optionally a body double. Work only on that task; record distractions instead of following them.",
      situation: "You want to begin but end up scrolling, wandering around, or preparing. The short sprint gives the task a clear time boundary.",
      why: "A manageable time limit reduces overwhelm. Body doubling can provide additional external structure and accountability.",
      timer: { seconds: 420, label: "Focus sprint", mode: "countdown", choices: [300, 420, 600] },
      fields: [
        { key: "focusTask", label: "My one task", type: "textarea", wide: true },
        { key: "bodyDouble", label: "My body double", type: "radio", wide: true, options: ["person in the room", "video call", "online focus room", "work-with-me video", "not needed today"] },
        { key: "distractions", label: "Parked distractions", type: "textarea" },
        { key: "sprintResult", label: "My result after the sprint", type: "textarea" },
      ],
      close: "I completed at least one focus sprint today.",
    },
    {
      day: 17, week: 3, title: "Plan Around Your Energy", page: "130", duration: "4 min", toolIds: [17],
      purpose: "Not every day brings the same amount of energy. Today, you adapt at least one expectation to your actual state.",
      step: "Choose LOW, MEDIUM, or HIGH. On LOW, reduce demands; on MEDIUM, handle routines; on HIGH, use your energy for demanding or creative tasks.",
      situation: "During PMS, stress, or low-energy phases, everything gets louder. Yet you expect the same output as on a good day—and judge yourself when it does not happen.",
      why: "Energy-based planning replaces fighting your current state with more realistic management of your day.",
      fields: [
        { key: "energy", label: "My energy today", type: "radio", wide: true, options: ["LOW · little energy", "MEDIUM · routine tasks are possible", "HIGH · good concentration"] },
        { key: "adjustExpectation", label: "The expectation I will adjust", type: "textarea" },
        { key: "goodEnough", label: "This can be good enough today", type: "textarea" },
      ],
      close: "I adjusted one expectation to my energy level.",
    },
    {
      day: 18, week: 3, title: "Your Energy Stabilizer", page: "133", duration: "5 min", toolIds: [18],
      purpose: "When your body gets too little fluid or regular nourishment, your mind may also feel more unsettled. Today, you prepare a simple stabilizer.",
      step: "Plan a visible hydration anchor and a protein snack or scheduled mini-meal for your day.",
      situation: "The afternoon crash arrives. You become more irritable, ruminate more, or seek quick stimulation. Today, you plan ahead instead of reacting only after the dip.",
      why: "Regular nourishment can support steadier energy and reduce one additional strain that contributes to inner restlessness.",
      note: "If you have health questions, discuss supplements or major dietary changes with a qualified professional.",
      fields: [
        { key: "hydration", label: "My hydration anchor", type: "radio", wide: true, options: ["keep a bottle visible", "set a reminder", "keep a drink at my workspace"] },
        { key: "snack", label: "My snack or mini-meal", type: "text" },
        { key: "snackTime", label: "My time", type: "time" },
        { key: "visiblePlace", label: "My visible storage spot", type: "text", wide: true },
      ],
      close: "My stabilizer is prepared.",
    },
    {
      day: 19, week: 3, title: "Release Physically for 90 Seconds", page: "144", duration: "90 sec", toolIds: [19],
      purpose: "Strong tension does not live only in your thoughts. It also appears in your body. Today, you first channel that energy physically.",
      step: "Do ten squats, shake out or walk for twenty seconds, then do ten more squats. Adapt everything to your body and abilities.",
      situation: "You feel anger, frustration, or a strong impulse and want to react immediately. First, you move your body for 90 seconds.",
      why: "Movement can reduce physical tension. This creates a short interruption between impulse and response.",
      timer: { seconds: 90, label: "Physical pause", mode: "countdown" },
      fields: [
        { key: "movement", label: "My safe option", type: "radio", wide: true, options: ["squats", "brisk walking", "wall pushes", "vigorous shaking"] },
        { key: "sequence", label: "Sequence", type: "checkbox", wide: true, options: ["first movement", "20 seconds shaking or walking", "second movement"] },
      ],
      close: "I took a physical pause before responding.",
    },
    {
      day: 20, week: 3, title: "Box Breathing", page: "146", duration: "2 min", toolIds: [20],
      purpose: "Before difficult calls, feedback, or administrative appointments, your body may already sound the alarm. Today, you regulate your breathing first.",
      step: "Breathe in for four seconds, hold for four, breathe out for four, and hold for four. Breathe without forcing it and shorten the counts if four seconds feels uncomfortable.",
      situation: "Before a phone call, feedback, or an appointment with an agency, the alarm rises so high that you avoid the task.",
      why: "Slow, conscious breathing can send a calming signal to the body and lower the perceived alarm level.",
      timer: { seconds: 120, label: "Box Breathing", mode: "breathing" },
      fields: [
        { key: "nextTask", label: "My task immediately after breathing", type: "textarea", wide: true, placeholder: "One small next step" },
      ],
      close: "I breathed consciously for two minutes.",
    },
    {
      day: 21, week: 3, title: "Three Boxes and a Phone Script", page: "172 and 174", duration: "10 min", toolIds: [23, 24],
      purpose: "Administrative tasks become easier when you do not have to decide everything at once. Today, you separate sorting from acting.",
      step: "Sort one document into NOW, WAITING, or ARCHIVE. Then write three simple sentences for a possible phone call.",
      situation: "A letter has been lying unopened for weeks. At the same time, the thought of a possible phone call blocks you. Today, you break both into small steps.",
      why: "The system reduces decision load. The script keeps you from having to hold all important information in your head spontaneously during the call.",
      fields: [
        { key: "document", label: "My document today", type: "text", wide: true },
        { key: "box", label: "My box", type: "radio", wide: true, options: ["📥 NOW · action needed", "⏳ WAITING · reply or deadline pending", "📁 ARCHIVE · keep only"] },
        { key: "callReason", label: "1. I am calling about …", type: "textarea" },
        { key: "reference", label: "2. Reference or customer number", type: "text" },
        { key: "request", label: "3. I need the following information …", type: "textarea", wide: true },
        { key: "bestTool", label: "The most helpful tool was", type: "textarea" },
        { key: "keepTool", label: "The tool I want to keep using", type: "textarea" },
        { key: "proud", label: "What I am proud of", type: "textarea", wide: true },
      ],
      close: "I completed the 21-day plan.",
    },
  ];

  const tools = [
    [1, "Strength Detectives", "Self-worth", 1, "Collect facts against the automatic negativity filter.", "20"],
    [2, "Name the Critic", "Thoughts", 2, "Create distance between you and the critical voice.", "23"],
    [3, "Dopamine Pause", "Immediate help", 3, "Stop new stimulation for three minutes.", "34"],
    [4, "5–4–3–2–1 Grounding", "Immediate help", 4, "Use your senses to bring attention back to the present.", "37"],
    [5, "Sensory Audit", "Sensory input", 5, "Identify and reduce hidden sources of stress.", "48"],
    [6, "Safe-Space Box", "Sensory input", 6, "Prepare aids that are immediately within reach.", "49"],
    [7, "Idea Sluice", "Focus", 7, "Park thoughts safely instead of following them immediately.", "62"],
    [8, "Analog Mind Mapping", "Focus", 8, "Make an inner knot visible and sortable.", "63"],
    [9, "Unmasking Traffic Light", "Relationships", 9, "Recognize the energy cost of different environments.", "73"],
    [10, "RSD SOS", "Immediate help", 10, "Separate observation, interpretation, and response.", "75"],
    [11, "Time-Out Gesture", "Relationships", 11, "Interrupt escalation and return safely.", "87"],
    [12, "Dopamine Check-In", "Relationships", 12, "Make good moments, hard moments, and needs discussable.", "89"],
    [13, "Minimum Friction", "Daily life", 13, "Adapt systems to real life.", "102"],
    [14, "15-Minute Flash Routine", "Daily life", 14, "Use a short, visible reset to get moving.", "104"],
    [15, "Eat the Frog · ADHD-Modified", "Work", 15, "Reduce the barrier to a one-minute start.", "117"],
    [16, "Focus Timer & Body Doubling", "Work", 16, "Combine a time limit with external structure.", "118"],
    [17, "Cycle Planner", "Energy", 17, "Adapt expectations to your current energy.", "130"],
    [18, "Nutrition & Dopamine Support", "Energy", 18, "Plan simple, visible energy stabilizers.", "133"],
    [19, "Physical Release", "Immediate help", 19, "Lower strong physical activation before responding.", "144"],
    [20, "Box Breathing", "Immediate help", 20, "Use conscious breathing to lower the alarm level.", "146"],
    [21, "Parallel Working", "Relationships", null, "Have important conversations during light shared movement.", "138"],
    [22, "Needs Translation List", "Relationships", null, "Translate visible behavior and inner reality together.", "140"],
    [23, "Three-Box Sorting System", "Admin", 21, "Pre-sort mail with only three decisions.", "172"],
    [24, "Phone Script", "Admin", 21, "Write down key sentences before an administrative call.", "174"],
    [25, "Needs Manifesto", "Self-advocacy", null, "Make your own requirements concrete and communicable.", "167"],
    [26, "Build a Support Network", "Self-advocacy", null, "Deliberately build low-stimulation support.", "169"],
  ].map(([id, title, category, day, summary, page]) => ({ id, title, category, day, summary, page }));

  const supportTools = {
    21: {
      intro: "Being side by side can be easier for an ADHD brain than sitting face to face. A simple activity provides enough activation to keep the conversation channel open.",
      steps: ["Choose a light parallel activity: walking, cooking, or sorting.", "Say: ‘I want to tell you something important.’", "Do not expect constant eye contact.", "Use this format outside conflict as well."],
    },
    22: {
      intro: "The list makes translation errors visible before they turn into blame.",
      steps: ["What I do: the visible behavior.", "What you may think: the possible interpretation.", "What is actually happening: the ADHD reality.", "Start with three recurring situations."],
    },
    25: {
      intro: "A need becomes easier to discuss when it is concrete rather than vague.",
      steps: ["What do I need to function well?", "How do I notice when it is missing?", "Which small, concrete adjustment helps?", "Share only one point with a safe person first."],
    },
    26: {
      intro: "Support does not have to be loud or constant. One small, reliable connection is a real network.",
      steps: ["Choose exactly one person, group, or professional service.", "Turn off notifications in online groups.", "Plan a low frequency, such as once a week.", "Reading along counts—active participation is optional."],
    },
  };

  const sosRoutes = [
    { id: "noise", title: "My mind is racing", subtitle: "Too many thoughts or too much input", color: "#ffae22", icon: "∞", day: 3, steps: ["Put away new stimulation for three minutes.", "Place both feet on the floor.", "Start the dopamine pause—you do not have to solve anything right now."] },
    { id: "overload", title: "Everything is too much", subtitle: "Sensory overload or close to shutdown", color: "#32d2ef", icon: "◌", day: 6, steps: ["Reduce light, sound, or touch first.", "Take exactly one item from your safe-space box.", "Allow yourself to withdraw before making another decision."] },
    { id: "rejection", title: "It feels like rejection", subtitle: "A message, a look, or no reply", color: "#db55ff", icon: "?", day: 10, steps: ["Name it: ‘This might be RSD right now.’", "Separate the observable fact from your interpretation.", "Find two neutral explanations and wait before responding."] },
    { id: "conflict", title: "A conversation is tipping", subtitle: "Heat, pressure, or risk of escalation", color: "#ff6271", icon: "Ⅱ", day: 11, steps: ["Use your time-out gesture.", "Name a specific return time.", "Regulate your body first—solve the issue later."] },
    { id: "stuck", title: "I cannot get started", subtitle: "The task feels too large", color: "#50df99", icon: "›", day: 15, steps: ["Name only the one important task.", "Shrink the start to no more than one minute.", "Do only that step. Then you may decide again."] },
    { id: "impulse", title: "I want to react now", subtitle: "Anger, frustration, or a strong impulse", color: "#ff8d32", icon: "!", day: 19, steps: ["Put your phone out of reach.", "Move your body for 90 seconds in a way that fits you.", "Rate the tension again before deciding how to respond."] },
    { id: "admin", title: "Mail or a call has me blocked", subtitle: "Admin and deadline pressure", color: "#6e91ff", icon: "□", day: 21, steps: ["Open or pick up exactly one document.", "Sort it only into NOW, WAITING, or ARCHIVE.", "If a call is needed, write down three sentences first."] },
  ];

  return { weeks, days, tools, supportTools, sosRoutes };
})();
